In [2]:
import shutil
import re
import os
os.environ['TOKENIZERS_PARALLELISM'] = "true"
from transformers import AutoTokenizer, AutoModelForMaskedLM
from cltk.sentence.lat import LatinPunktSentenceTokenizer
import torch
from torch.nn.utils.rnn import pad_sequence

In [3]:
tokenizer = AutoTokenizer.from_pretrained("pnadel/latin_tokenizer") #"pnadel/LatinBERT")
model = AutoModelForMaskedLM.from_pretrained("pnadel/LatinBERT")

In [4]:
#!curl https://sciencedata.dk/public/87394f685b79e7f1ebd4a7ead2b4941c/noscemus_raw.zip -o ../data/large_data/noscemus_raw.zip
# shutil.unpack_archive("../data/large_data/noscemus_raw.zip", "../data/large_data/noscemus_raw")

In [5]:
def text_cleaner(rawtext):
    cleantext = rawtext.replace("¬\n", "").replace("\n", " ").replace("ß", "ss").replace("ij","ii")
    cleantext = " ".join([t[0] + t[1:].lower() for t in cleantext.split()])
    cleantext = re.sub("\s\s+", " ", cleantext)
    return cleantext

In [6]:
filenames = os.listdir("../data/large_data/noscemus_raw")

In [10]:
fn = filenames[3]
fn

'694898.txt'

In [11]:
with open("../data/large_data/noscemus_raw/" + fn, "r") as f:
    text = f.read()

In [12]:
text = text_cleaner(text)
text[:200]

'V Homae Bartholini De Usu Medico Observationes variae. Accessit D. Erasmi Bartholini Viv E Figura I Dissertatio, cum Operum Authoris Catalogo. E λη λὴν ) Hafniae Typis Matthiae Godicchii, Sumptibus Pe'

In [13]:
corpus = LatinPunktSentenceTokenizer().tokenize(text)
corpus[1:4]

['Accessit D. Erasmi Bartholini Viv E Figura I Dissertatio, cum Operum Authoris Catalogo.',
 'E λη λὴν ) Hafniae Typis Matthiae Godicchii, Sumptibus Petri Haubold, Bibl.',
 'cclo Ioc Lxi.']

In [14]:
#tokenizer.pad_token = tokenizer.eos_token
tokenized_corpus = [tokenizer.encode(sentence, return_tensors="pt") for sentence in corpus]

In [15]:
tokenized_corpus[1:4]

[tensor([[   18,  1678,    63,     8,   211,   128,  3208,   244,   570,  8995,
            118,    36,    63,   118,    22,   633,    63, 13041,    77,  5823,
              6,   201,   177,    78,   198,    23,   500,    83,   145,   425,
            236,     8]]),
 tensor([[6418,   53, 8490, 6418,   53, 8494,   48, 8492, 1416, 1226,   28,  451,
            63,   38, 1505,  232,  570,  451, 1417,  127,  380,  657,    6,  746,
            30,  629,  117,  120,   83,  228,  171,   19,    6,  118,   17,   26,
             8]]),
 tensor([[  18,   18,  425,  327, 2010,   24,    8]])]

In [16]:
max_len = max(len(seq[0]) for seq in tokenized_corpus)
padded_corpus = torch.stack([torch.cat([seq, torch.zeros((1, max_len - len(seq[0])))], dim=1) for seq in tokenized_corpus])
padded_corpus = padded_corpus.squeeze(1)
padded_corpus = padded_corpus.long()

In [17]:
padded_corpus.shape

torch.Size([3529, 206])

In [87]:
# Pass the padded corpus through the model
with torch.no_grad():
    outputs = model(input_ids=padded_corpus)

In [89]:
hidden_states = outputs.hidden_states[-1]  # Access the last layer's hidden states


TypeError: 'NoneType' object is not subscriptable

In [35]:
mask_token_id = tokenizer.mask_token_id if tokenizer.mask_token_id is not None else tokenizer.add_tokens("[MASK]")

tokens = tokenizer.encode(text, return_tensors="pt")

In [38]:
masked_indices = torch.bernoulli(torch.full(tokens.shape, 0.15)).bool()
masked_tokens = tokens.clone()
# Use torch.where to replace masked tokens
masked_tokens = torch.where(masked_indices, torch.tensor(mask_token_id), masked_tokens)

In [39]:
corpus = ["audentes forsque deusque iuvat", 
          "audentis fortuna iuvat, piger ipse sibi opstat",
          "audentes in tela ruunt",
          "audentes facit amissae spes lapsa salutis, succurruntque"]
tokenized_corpus = [tokenizer.encode(sentence, return_tensors="pt") for sentence in corpus]

In [40]:
tokenized_corpus

[tensor([[1127,  535, 5545,  135,  980,  135, 5073]]),
 tensor([[ 1127,   540,  1404,  5073,     6, 13307,    77,   694,   556,   302,
           2740]]),
 tensor([[ 1127,   535,   108,  3670, 11563]]),
 tensor([[ 1127,   535,  2617,   225,  9007,  1808, 22673,  5871,     6,  2927,
           1236,   157,   135]])]

In [ ]:
for fn in os.listdir("../data/large_data/noscemus_raw"):
    try:
        with open("../data/large_data/sents_lemmata/{}.txt".format(fn), "r") as f:
            text = f.read()
        text = text_cleaner(text)
        # text_sentence_vectors = []
        # for each sentence in the text
            # apply the bert vectors on it
            # add the sentence to a list of vectorized sentences
            # text_sentence_vectors.append()
        # save the file vectors into its own folder or to sciencedata  (following 
    except:
        pass

In [ ]:

!python3 scripts/gen_berts.py --bertPath models/latin_bert/ --tokenizerPath models/subword_tokenizer_latin/latin.subword.encoder > berts.output.txt
